version: '3'
services:
    api:
        # image: 
        build:
            dockerfile: Dockerfile
            context: .
    # redis-server:
    #    image: redis:latest  
    #    ports:
    #        - "6379:6379"
    