version: '3'
services:
    api:
        # image: 
        build:
            dockerfile: Dockerfile
            context: .
        environment: 
            REDIS_HOST: redis
            REDIS_PORT: 6379
    # redis-server:
    #    image: redis:latest  
    #    ports:
    #        - "6379:6379"
    