version: "3.8"
services:
    api:
        # image: 
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            # DATABASE_URL: postgres://user:password@db:5432/db
            NODE_ENV: development
            PORT: 3000
            POSTGRES_HOST: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
            POSTGRES_DB: db
            POSTGRES_PORT: 5432
        ports:
            - "8080:3000"

    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
